# https://taskfile.dev

version: "3"

vars:
  APP_GMF: ./gmf
  APP_GOFILE: cmd/gmf/gmf.go
  APP_NAME: gmf
  APP_VERSION: 2.0.8
  APP_BUILD:
    sh: git log -n 1 --format=%H
  APP_DATE:
    sh: git log -n 1 --format=%aI
  LDFLAGS: -ldflags " -X main.Version={{.APP_VERSION}} -X main.Build={{.APP_BUILD}} -X main.DateBuild={{.APP_DATE}}"
  GO_MODULE:
    sh: go mod why -m | {{.APP_GMF}} stdin -n 1 -r  "^# (.+)\$" "\$1"

tasks:
  echo:
    cmds:
      - echo "{{.GO_MODULE}}"
  dev:
    cmds:
      - task: build
      - ./gmf {{.CLI_ARGS}}
  build:
    cmds:
      - go build {{.LDFLAGS}} -o gmf {{.APP_GOFILE}}

  version:
    cmds:
      - task dev -- version -i
  gitpush:
    cmds:
      - task: build
      - task set-gomain
      - git add .
      - git cpush
  mod:
    cmds:
      - go mod tidy
      - go mod vendor

  install:
    cmds:
      - go install {{.GO_MODULE}}/cmd/gmf@latest

  set-gomain:
    cmds:
      - task: build
      - ./gmf tail {{.APP_GOFILE}} | ./gmf stdin  -r '^(\s+AppName +string = )("\w*")$' '$1"{{.APP_NAME}}"' > {{.APP_GOFILE}}-tmp
      - mv {{.APP_GOFILE}}-tmp {{.APP_GOFILE}}
      - ./gmf tail {{.APP_GOFILE}} | ./gmf stdin  -r '^(\s+Version +string = )("\w*")$' '$1"{{.APP_VERSION}}"' > {{.APP_GOFILE}}-tmp
      - mv {{.APP_GOFILE}}-tmp {{.APP_GOFILE}}
      - ./gmf tail {{.APP_GOFILE}} | ./gmf stdin  -r '^(\s+Build +string = )("\w*")$' '$1"{{.APP_BUILD}}"' > {{.APP_GOFILE}}-tmp
      - mv {{.APP_GOFILE}}-tmp {{.APP_GOFILE}}
      - ./gmf tail {{.APP_GOFILE}} | ./gmf stdin  -r '^(\s+DateBuild +string = )("\w*")$' '$1"{{.APP_DATE}}"' > {{.APP_GOFILE}}-tmp
      - mv {{.APP_GOFILE}}-tmp {{.APP_GOFILE}}
